# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downr1n.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 340)
        MainWindow.setMinimumSize(QtCore.QSize(470, 340))
        MainWindow.setMaximumSize(QtCore.QSize(480, 340))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.IPSWButton = QtWidgets.QPushButton(self.layoutWidget)
        self.IPSWButton.setObjectName("IPSWButton")
        self.gridLayout.addWidget(self.IPSWButton, 1, 1, 1, 1)
        self.IPSWLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.IPSWLineEdit.setObjectName("IPSWLineEdit")
        self.gridLayout.addWidget(self.IPSWLineEdit, 1, 0, 1, 1)
        self.IPSWLabel = QtWidgets.QLabel(self.layoutWidget)
        self.IPSWLabel.setMaximumSize(QtCore.QSize(600, 30))
        self.IPSWLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.IPSWLabel.setObjectName("IPSWLabel")
        self.gridLayout.addWidget(self.IPSWLabel, 0, 0, 1, 2)
        self.IdentifierLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 465, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StartButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 35))
        self.StartButton.setObjectName("StartButton")
        self.gridLayout_2.addWidget(self.StartButton, 1, 0, 1, 7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.BootMode = QtWidgets.QRadioButton(self.layoutWidget1)
        self.BootMode.setObjectName("BootMode")
        self.gridLayout_2.addWidget(self.BootMode, 0, 4, 1, 1)
        self.RestoreMode = QtWidgets.QRadioButton(self.layoutWidget1)
        self.RestoreMode.setEnabled(True)
        self.RestoreMode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RestoreMode.setAutoFillBackground(False)
        self.RestoreMode.setChecked(True)
        self.RestoreMode.setObjectName("RestoreMode")
        self.gridLayout_2.addWidget(self.RestoreMode, 0, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.StartButton.clicked.connect(MainWindow.StartButton_clicked) # type: ignore
        self.IPSWButton.clicked.connect(MainWindow.IPSWPath_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.IPSWLineEdit, self.IPSWButton)
        MainWindow.setTabOrder(self.RestoreMode, self.BootMode)
        MainWindow.setTabOrder(self.RestoreMode, self.BootMode)
        MainWindow.setTabOrder(self.BootMode, self.StartButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "downr1n - GUI"))
        self.IPSWButton.setText(_translate("MainWindow", "..."))
        self.IPSWLabel.setText(_translate("MainWindow", "IPSW Path"))
        self.StartButton.setText(_translate("MainWindow", "Start!"))
        self.BootMode.setText(_translate("MainWindow", "Boot"))
        self.RestoreMode.setText(_translate("MainWindow", "Restore"))
